### ISSUE TITLE
no header.sh

### ISSUE THREAD

**Issue by chenhaiyan** [Kyligence/kylin-on-parquet-v2#180]
${SOURCE_CODE_HOME}/build/script/download-spark.sh
source $(cd -P -- "$(dirname -- "$0")" && pwd -P)/header.sh
there is no header.sh file

**Comment by RupengWang** [comment]
If you want to download spark, you can using the following command:
```shell
wget https://download-resource.s3.cn-north-1.amazonaws.com.cn/osspark/spark-2.4.1-os-kylin-r3.tgz
```
This script is using for binary package, you can download spark with this script after packaging. Then spark will be decompressed to ${KYLIN_HOME}/spark
```shell
${KYLIN_HOME}/bin/down-spark.sh
```
